from tqdm import tqdm
from faker import Faker
from datetime import datetime, timedelta
import random
import pandas as pd
import sqlite3

fake = Faker("en_US")

def generate_suffix():
    return fake.suffix() if random.random() < 0.03 else None


def generate_middle():
    return fake.first_name() if random.random() < 0.32 else None


def generate_phone():
    area_code = fake.random_number(digits=3, fix_len=True)
    central_office_code = fake.random_number(digits=3, fix_len=True)
    line_number = fake.random_number(digits=4, fix_len=True)
    return f"{area_code}-{central_office_code}-{line_number}"


def generate_address():
    street_num = random.randint(1, 5999)
    street_name = [
        '10th',
        '11th',
        '12th',
        '13th',
        '14th',
        '15th',
        '16th',
        '17th',
        '18th',
        '19th',
        '1st',
        '20th',
        '21st',
        '22nd',
        '23rd',
        '24th',
        '25th',
        '26th',
        '27th',
        '28th',
        '29th',
        '2nd',
        '30th',
        '31st',
        '32nd',
        '33rd',
        '34th',
        '35th',
        '36th',
        '37th',
        '38th',
        '39th',
        '3rd',
        '40th',
        '41st',
        '42nd',
        '43rd',
        '44th',
        '45th',
        '46th',
        '47th',
        '48th',
        '4th',
        '5th',
        '6th',
        '7th',
        '8th',
        '9th',
        'A',
        'Abbey',
        'Acacia',
        'Acadia',
        'Acevedo',
        'Acme',
        'Acorn',
        'Acton',
        'Ada',
        'Adair',
        'Adam',
        'Addison',
        'Adele',
        'Admiral',
        'Adolph Sutro',
        'Aerial',
        'Agnon',
        'Agua',
        'Ahern',
        'Al Scoma',
        'Alabama',
        'Aladdin',
        'Alameda',
        'Alana',
        'Albatross',
        'Alberta',
        'Albion',
        'Alder',
        'Alemany',
        'Alert',
        'Alhambra',
        'Alice B Toklas',
        'Allen',
        'Allison',
        'Allston',
        'Alma',
        'Almaden',
        'Aloha',
        'Alpha',
        'Alpine',
        'Alta',
        'Alta Mar',
        'Alta Vista',
        'Alton',
        'Alvarado',
        'Alviso',
        'Alvord',
        'Amador',
        'Amatista',
        'Amatury',
        'Amazon',
        'Amber',
        'Ambrose Bierce',
        'Ames',
        'Amethyst',
        'Amherst',
        'Amity',
        'Anderson',
        'Andover',
        'Andrew',
        'Angelos',
        'Anglo',
        'Ankeny',
        'Annapolis',
        'Annie',
        'Anson',
        'Anthony',
        'Antonio',
        'Anza',
        'Anzavista',
        'Apollo',
        'Apparel',
        'Appleton',
        'Aptos',
        'Aquavista',
        'Arago',
        'Arballo',
        'Arbol',
        'Arbor',
        'Arch',
        'Arco',
        'Ardath',
        'Ardenwood',
        'Arelious Walker',
        'Arellano',
        'Argent',
        'Argonaut',
        'Arguello',
        'Arkansas',
        'Arleta',
        'Arlington',
        'Armistead',
        'Armory',
        'Armstrong',
        'Arnold',
        'Arroyo',
        'Arthur',
        'Ash',
        'Ashburton',
        'Ashbury',
        'Ashton',
        'Ashwood',
        'Aspen',
        'Atalaya',
        'Athens',
        'Atoll',
        'Attridge',
        'Auburn',
        'August',
        'Augusta',
        'Austin',
        'Auto',
        'Automobile',
        'Avalon',
        'Avenue G',
        'Avery',
        'Avila',
        'Avoca',
        'Avocet',
        'Avon',
        'Aztec',
        'Bache',
        'Bacon',
        'Baden',
        'Badger',
        'Baker',
        'Balance',
        'Balboa',
        'Balceta',
        'Baldwin',
        'Balhi',
        'Balmy',
        'Baltimore',
        'Banbury',
        'Bancroft',
        'Bank',
        'Banks',
        'Bannan',
        'Banneker',
        'Bannock',
        'Barcelona',
        'Barnard',
        'Barneveld',
        'Barry',
        'Bartlett',
        'Bartol',
        'Bass',
        'Battery',
        'Baxter',
        'Bay',
        'Bay Shore',
        'Bay View',
        'Bayside',
        'Bayside Village',
        'Bayview',
        'Bayview Park',
        'Baywood',
        'Beach',
        'Beachmont',
        'Beacon',
        'Beale',
        'Beatrice',
        'Beaumont',
        'Beaver',
        'Beckett',
        'Bedford',
        'Beeman',
        'Behr',
        'Beideman',
        'Belcher',
        'Belden',
        'Belgrave',
        'Bell',
        'Bella Vista',
        'Bellair',
        'Belle',
        'Belles',
        'Bellevue',
        'Belmont',
        'Belvedere',
        'Bemis',
        'Bengal',
        'Bennington',
        'Benton',
        'Bepler',
        'Bergen',
        'Berkeley',
        'Berkshire',
        'Bernal Heights',
        'Bernard',
        'Bernice',
        'Bernice Rodgers',
        'Berry',
        'Bertha',
        'Bertie Minor',
        'Bertita',
        'Berwick',
        'Bessie',
        'Beulah',
        'Beverly',
        'Bigelow',
        'Bigler',
        'Birch',
        'Birchwood',
        'Bird',
        'Birmingham',
        'Bishop',
        'Bitting',
        'Black',
        'Blackstone',
        'Blair',
        'Blairwood',
        'Blake',
        'Blanche',
        'Blandy',
        'Blanken',
        'Blatchford',
        'Bliss',
        'Blossom',
        'Bluxome',
        'Blythdale',
        'Boalt',
        'Boardman',
        'Bob Kaufman',
        'Bocana',
        'Bonifacio',
        'Bonita',
        'Bonnie Brae',
        'Bonview',
        'Borica',
        'Bosworth',
        'Boutwell',
        'Bowdoin',
        'Bowley',
        'Bowling Green',
        'Bowman',
        'Boyd',
        'Boylston',
        'Boynton',
        'Bradford',
        'Brady',
        'Braghetta',
        'Brannan',
        'Brant',
        'Brazil',
        'Breen',
        'Brentwood',
        'Bret Harte',
        'Brewster',
        'Brice',
        'Bridgeview',
        'Bright',
        'Brighton',
        'Bristol',
        'Britton',
        'Broad',
        'Broadmoor',
        'Broadway',
        'Broderick',
        'Bromley',
        'Brompton',
        'Bronte',
        'Brook',
        'Brookdale',
        'Brookhaven',
        'Brooklyn',
        'Brooks',
        'Brosnan',
        'Brotherhood',
        'Brown',
        'Bruce',
        'Brumiss',
        'Brunswick',
        'Brush',
        'Brussels',
        'Bruton',
        'Bryant',
        'Bucareli',
        'Buchanan',
        'Buckingham',
        'Buena Vista',
        'Burgoyne',
        'Burke',
        'Burlwood',
        'Burnett',
        'Burns',
        'Burnside',
        'Burr',
        'Burritt',
        'Burrows',
        'Bush',
        'Butte',
        'Byron',
        'Byxbee',
        'C',
        'Cabrillo',
        'Cadell',
        'Caine',
        'Caire',
        'Caledonia',
        'Calgary',
        'Calhoun',
        'California',
        'Calvert',
        'Cambon',
        'Cambridge',
        'Camellia',
        'Cameo',
        'Cameron',
        'Camp',
        'Campbell',
        'Campton',
        'Campus',
        'Canby',
        'Candlestick Cove',
        'Canyon',
        'Capistrano',
        'Capitol',
        'Capp',
        'Capra',
        'Card',
        'Cardenas',
        'Cargo',
        'Carl',
        'Carmel',
        'Carmelita',
        'Carnelian',
        'Carolina',
        'Carpenter',
        'Carr',
        'Carrie',
        'Carrizal',
        'Carroll',
        'Carson',
        'Carter',
        'Carver',
        'Casa',
        'Cascade',
        'Case',
        'Caselli',
        'Cashmere',
        'Casitas',
        'Cassandra',
        'Castelo',
        'Castenada',
        'Castillo',
        'Castle',
        'Castle Manor',
        'Castro',
        'Catalina',
        'Catherine',
        'Cayuga',
        'Ccsf Parking Lot',
        'Cecilia',
        'Cedar',
        'Cedro',
        'Central',
        'Central Magazine',
        'Century',
        'Ceres',
        'Cerritos',
        'Cervantes',
        'Cesar Chavez',
        'Cesar Chavez On',
        'Chabot',
        'Chain Of Lakes',
        'Chancery',
        'Channel',
        'Chapman',
        'Charles',
        'Charles J Brenham',
        'Charlton',
        'Charter Oak',
        'Chase',
        'Chatham',
        'Chattanooga',
        'Chaves',
        'Chenery',
        'Cherry',
        'Chesley',
        'Chester',
        'Chestnut',
        'Chicago',
        'Child',
        'Chilton',
        'China Basin',
        'Chinook',
        'Christmas Tree',
        'Christopher',
        'Chula',
        'Chumasero',
        'Church',
        'Cielito',
        'Circular',
        'Cityview',
        'Clairview',
        'Clara',
        'Claremont',
        'Clarence',
        'Clarendon',
        'Clarion',
        'Clarke',
        'Clarkson',
        'Claude',
        'Clay',
        'Clayton',
        'Clearfield',
        'Clearview',
        'Cleary',
        'Clement',
        'Clementina',
        'Cleo Rand',
        'Cleveland',
        'Clifford',
        'Clinton',
        'Clipper',
        'Clipper Cove',
        'Cloud',
        'Clover',
        'Clyde',
        'Cochrane',
        'Codman',
        'Cohen',
        'Colby',
        'Cole',
        'Coleman',
        'Coleridge',
        'Colin',
        'Colin P Kelly Jr',
        'Colleen',
        'College',
        'Collingwood',
        'Collins',
        'Colon',
        'Colonial',
        'Colton',
        'Columbia Square',
        'Columbus',
        'Colusa',
        'Comerford',
        'Commer',
        'Commercial',
        'Commonwealth',
        'Compton',
        'Concord',
        'Concourse',
        'Congdon',
        'Congo',
        'Conkling',
        'Connecticut',
        'Conrad',
        'Conservatory',
        'Constanso',
        'Continuum',
        'Converse',
        'Cook',
        'Cooper',
        'Copper',
        'Cora',
        'Coral',
        'Coralino',
        'Corbett',
        'Corbin',
        'Cordelia',
        'Cordova',
        'Corinne Woods',
        'Cornwall',
        'Corona',
        'Coronado',
        'Cortes',
        'Cortland',
        'Corwin',
        'Cosgrove',
        'Cosmo',
        'Coso',
        'Costa',
        'Cottage',
        'Cotter',
        'Country Club',
        'Coventry',
        'Cowell',
        'Cowles',
        'Cragmont',
        'Crags',
        'Craig',
        'Crane',
        'Cranleigh',
        'Craut',
        'Cravath',
        'Crescent',
        'Crescio',
        'Crespi',
        'Cresta Vista',
        'Crestlake',
        'Crestline',
        'Crestmont',
        'Crestwell',
        'Crisp',
        'Crissy Field',
        'Croaker',
        'Crook',
        'Cross',
        'Crossover',
        'Crown',
        'Crystal',
        'Cuba',
        'Cuesta',
        'Culebra',
        'Cumberland',
        'Cunningham',
        'Curtis',
        'Cushman',
        'Custer',
        'Custom House',
        'Cutler',
        'Cuvier',
        'Cypress',
        'Cyril Magnin',
        'Cyrus',
        'D',
        'Daggett',
        'Dakota',
        'Dalewood',
        'Daniel Burnham',
        'Danton',
        'Danvers',
        'Darien',
        'Darrell',
        'Dartmouth',
        'Dashiell Hammett',
        'Davenport',
        'Davidson',
        'Davis',
        'Dawnview',
        'Dawson',
        'Day',
        'De Boom',
        'De Forest',
        'De Haro',
        'De Long',
        'De Montfort',
        'De Soto',
        'De Wolf',
        'Dearborn',
        'Decatur',
        'Decker',
        'Dedman',
        'Deems',
        'Dehon',
        'Del Monte',
        'Del Sur',
        'Del Vale',
        'Delancey',
        'Delano',
        'Delaware',
        'Delgado',
        'Dellbrook',
        'Delmar',
        'Delta',
        'Deming',
        'Denslowe',
        'Derby',
        'Desmond',
        'Detroit',
        'Devonshire',
        'Dewey',
        'Dewitt',
        'Diamond',
        'Diamond Cove',
        'Diamond Heights',
        'Diana',
        'Diaz',
        'Dicha',
        'Dichiera',
        'Dickinson',
        'Digby',
        'Dirk Dirksen',
        'Divisadero',
        'Division',
        'Dixie',
        'Dock',
        'Dodge',
        'Dolores',
        'Dolphin',
        'Don Chee',
        'Donahue',
        'Donner',
        'Dorado',
        'Dorantes',
        'Dorcas',
        'Dorchester',
        'Dore',
        'Doric',
        'Dorland',
        'Dorman',
        'Dormitory',
        'Double Rock',
        'Douglass',
        'Dove',
        'Dow',
        'Downey',
        'Dr Carlton B Goodlett',
        'Dr Maya Angelou',
        'Dr Tom Waddell',
        'Drake',
        'Drumm',
        'Drummond',
        'Dublin',
        'Duboce',
        'Dudley',
        'Dukes',
        'Duncan',
        'Duncombe',
        'Dunlin',
        'Dunnes',
        'Dunshee',
        'Dunsmuir',
        'Dwight',
        'E',
        'Eagle',
        'Earl',
        'Earl Gage Jr',
        'Easement',
        'East',
        'East Beach',
        'East Crystal Cove',
        'East Fort Miley',
        'Eastman',
        'Eastwood',
        'Eaton',
        'Ecker',
        'Eddy',
        'Edgar',
        'Edgardo',
        'Edgehill',
        'Edgewood',
        'Edie',
        'Edinburgh',
        'Edith',
        'Edna',
        'Edward',
        'Egbert',
        'El Camino Del Mar',
        'El Dorado',
        'El Mirasol',
        'El Plazuela',
        'El Polin',
        'El Sereno',
        'El Verano',
        'Eldridge',
        'Elgin',
        'Elim',
        'Elizabeth',
        'Elk',
        'Ellert',
        'Ellington',
        'Elliot',
        'Ellis',
        'Ellsworth',
        'Elm',
        'Elmhurst',
        'Elmira',
        'Elmwood',
        'Elsie',
        'Elwood',
        'Emerald',
        'Emerald Cove',
        'Emerson',
        'Emery',
        'Emil',
        'Emma',
        'Emmett',
        'Encanto',
        'Encinal',
        'Encline',
        'English',
        'Enterprise',
        'Entrada',
        'Erie',
        'Erkson',
        'Ervine',
        'Escolta',
        'Escondido',
        'Esmeralda',
        'Espanola',
        'Esquina',
        'Essex',
        'Estero',
        'Eucalyptus',
        'Euclid',
        'Eugenia',
        'Eureka',
        'Evans',
        'Eve',
        'Evelyn',
        'Everglade',
        'Everson',
        'Ewer',
        'Ewing',
        'Excelsior',
        'Exchange',
        'Executive Park',
        'Exeter',
        'Exposition',
        'Fair',
        'Fair Oaks',
        'Fairbanks',
        'Fairfax',
        'Fairfield',
        'Fairmount',
        'Faith',
        'Fallon',
        'Falmouth',
        'Fanning',
        'Farallon',
        'Farallones',
        'Fargo',
        'Farnsworth',
        'Farnum',
        'Farragut',
        'Farview',
        'Fauntleroy',
        'Faxon',
        'Federal',
        'Felix',
        'Fell',
        'Fell Access',
        'Fella',
        'Felton',
        'Fenton',
        'Fern',
        'Fernandez',
        'Fernwood',
        'Fielding',
        'Fifth',
        'Filbert',
        'Fillmore',
        'Finley',
        'First',
        'Fisher',
        'Fitch',
        'Fitzgerald',
        'Flint',
        'Flood',
        'Flora',
        'Florence',
        'Florentine',
        'Florida',
        'Flounder',
        'Flournoy',
        'Flower',
        'Foerster',
        'Folsom',
        'Font',
        'Fontinella',
        'Foote',
        'Ford',
        'Forest',
        'Forest Hill',
        'Forest Knolls',
        'Forest Side',
        'Forest View',
        'Forsyth',
        'Fort Funston',
        'Fortuna',
        'Fountain',
        'Fowler',
        'France',
        'Francis',
        'Francisco',
        'Franconia',
        'Frank Norris',
        'Franklin',
        'Fratessa',
        'Fredela',
        'Frederick',
        'Fredson',
        'Freelon',
        'Freeman',
        'Fremont',
        'French',
        'Fresnel',
        'Fresno',
        'Frida Kahlo',
        'Friedell',
        'Friendship',
        'Front',
        'Fuente',
        'Fulton',
        'Funston',
        'Gabilan',
        'Gaiser',
        'Galewood',
        'Galilee',
        'Galindo',
        'Gallagher',
        'Galvez',
        'Gambier',
        'Garces',
        'Garcia',
        'Garden',
        'Gardener',
        'Gardenside',
        'Garfield',
        'Garlington',
        'Garnett',
        'Garrison',
        'Gates',
        'Gateview',
        'Gatun',
        'Gaven',
        'Gaviota',
        'Geary',
        'Gellert',
        'Gene Friend',
        'Genebern',
        'General Kennedy',
        'Geneva',
        'Gennessee',
        'Genoa',
        'George',
        'Georgia',
        'Gerke',
        'Germania',
        'Getz',
        'Giants',
        'Gibb',
        'Gibbon',
        'Gibson',
        'Gilbert',
        'Gillette',
        'Gilman',
        'Gilroy',
        'Girard',
        'Gladeview',
        'Gladiolus',
        'Gladstone',
        'Gladys',
        'Glen',
        'Glenbrook',
        'Glendale',
        'Glenhaven',
        'Glenview',
        'Globe',
        'Gloria',
        'Glover',
        'Godeus',
        'Goethe',
        'Goettingen',
        'Gold',
        'Gold Mine',
        'Goldberg',
        'Golden',
        'Golden Bell',
        'Golden Gate',
        'Golding',
        'Goleta',
        'Gonzalez',
        'Gordon',
        'Gorgas',
        'Gorham',
        'Gough',
        'Gould',
        'Grace',
        'Grafton',
        'Graham',
        'Granada',
        'Grand View',
        'Grant',
        'Granville',
        'Grattan',
        'Graystone',
        'Great',
        'Greely',
        'Green',
        'Greenough',
        'Greenview',
        'Greenwich',
        'Greenwood',
        'Grenard',
        'Griffith',
        'Grijalva',
        'Grote',
        'Grove',
        'Guerrero',
        'Guttenberg',
        'Guy',
        'H',
        'Habitat',
        'Hagiwara Tea Garden',
        'Hahn',
        'Haight',
        'Hale',
        'Halibut',
        'Hallam',
        'Halleck',
        'Halyburton',
        'Hamerton',
        'Hamilton',
        'Hamlin',
        'Hampshire',
        'Hancock',
        'Hangah',
        'Hanover',
        'Harbor',
        'Hardie',
        'Harding',
        'Hare',
        'Harkness',
        'Harlan',
        'Harlem',
        'Harlow',
        'Harmonia',
        'Harney',
        'Harold',
        'Harper',
        'Harriet',
        'Harrington',
        'Harris',
        'Harrison',
        'Harry',
        'Hartford',
        'Harvard',
        'Hastings',
        'Hattie',
        'Havelock',
        'Havens',
        'Havenside',
        'Hawes',
        'Hawkins',
        'Hawthorne',
        'Hayes',
        'Hays',
        'Hayward',
        'Hazelwood',
        'Head',
        'Healy',
        'Hearst',
        'Heather',
        'Helen',
        'Helena',
        'Hemlock',
        'Hemway',
        'Henry',
        'Henry Adams',
        'Heritage',
        'Hermann',
        'Hernandez',
        'Heron',
        'Hester',
        'Heyman',
        'Hickory',
        'Hicks',
        'Hidalgo',
        'High',
        'Highland',
        'Higuera',
        'Hiliritas',
        'Hill',
        'Hill Point',
        'Hillcrest',
        'Hillside',
        'Hillview',
        'Hillway',
        'Hilton',
        'Himmelmann',
        'Hitchcock',
        'Hobart',
        'Hodges',
        'Hoff',
        'Hoffman',
        'Holladay',
        'Holland',
        'Hollis',
        'Hollister',
        'Holloway',
        'Holly Park',
        'Hollywood',
        'Holyoke',
        'Homer',
        'Homestead',
        'Homewood',
        'Hooker',
        'Hooper',
        'Hopkins',
        'Horace',
        'Horne',
        'Hotaling',
        'Houston',
        'Howard',
        'Howth',
        'Hubbell',
        'Hudson',
        'Hugo',
        'Hulbert',
        'Humboldt',
        'Hunt',
        'Hunter',
        'Hunters Point',
        'Huntington',
        'Huron',
        'Hussey',
        'Hutchins',
        'Icehouse',
        'Idora',
        'Ignacio',
        'Illinois',
        'Ils',
        'Imperial',
        'Ina',
        'Inca',
        'Incinerator',
        'India',
        'Indiana',
        'Indies',
        'Industrial',
        'Infantry',
        'Ingalls',
        'Ingerson',
        'Ingleside',
        'Innes',
        'Inverness',
        'Iowa',
        'Iris',
        'Iron',
        'Ironwood',
        'Irving',
        'Irwin',
        'Isadora Duncan',
        'Isis',
        'Islais',
        'Isola',
        'Issleib',
        'Italy',
        'Ivy',
        'J',
        'Jack Balestreri',
        'Jack Kerouac',
        'Jack London',
        'Jack Micheline',
        'Jackson',
        'Jade',
        'Jakey',
        'James',
        'Jamestown',
        'Jansen',
        'Jarboe',
        'Jason',
        'Jasper',
        'Jauss',
        'Java',
        'Jean',
        'Jeff Adachi',
        'Jefferson',
        'Jennifer',
        'Jennings',
        'Jerome',
        'Jerrold',
        'Jersey',
        'Jessie',
        'Jessie East',
        'Jessie West',
        'Jewett',
        'John',
        'John F Kennedy',
        'John F Shelley',
        'John Maher',
        'John Muir',
        'Johnson',
        'Johnstone',
        'Joice',
        'Jones',
        'Joost',
        'Jordan',
        'Jose Sarria',
        'Josepha',
        'Josiah',
        'Joy',
        'Juan Bautista',
        'Juanita',
        'Judah',
        'Judson',
        'Jules',
        'Julia',
        'Julian',
        'Julius',
        'Junior',
        'Juniper',
        'Junipero Serra',
        'Juri',
        'Justin',
        'Kalmanovitz',
        'Kamille',
        'Kansas',
        'Kaplan',
        'Karen',
        'Kate',
        'Kearny',
        'Keith',
        'Kelham',
        'Kelloch',
        'Kempton',
        'Kendall',
        'Kennedy',
        'Kenneth Rexroth',
        'Kenny',
        'Kensington',
        'Kent',
        'Kenwood',
        'Keppler',
        'Kern',
        'Key',
        'Keyes',
        'Keystone',
        'Kezar',
        'Kimball',
        'King',
        'Kingston',
        'Kinzey',
        'Kirkham',
        'Kirkwood',
        'Kiska',
        'Kissling',
        'Kittredge',
        'Knockash',
        'Knollview',
        'Knott',
        'Kobbe',
        'Kohler',
        'Koret',
        'Kramer',
        'Krausgrill',
        'Kronquist',
        'La Avanzada',
        'La Bica',
        'La Ferrera',
        'La Grande',
        'La Playa',
        'La Salle',
        'Lafayette',
        'Laguna',
        'Laguna Honda',
        'Lagunitas',
        'Laidley',
        'Lake',
        'Lake Forest',
        'Lake Merced',
        'Lake Merced Hill',
        'Lakeshore',
        'Lakeview',
        'Lakewood',
        'Lamartine',
        'Lamson',
        'Lancaster',
        'Landers',
        'Lane',
        'Langdon',
        'Langton',
        'Lansdale',
        'Lansing',
        'Lapham',
        'Lapidge',
        'Lapu-Lapu',
        'Larch',
        'Larkin',
        'Las Villas',
        'Laskie',
        'Lassen',
        'Lathrop',
        'Latona',
        'Laura',
        'Laurel',
        'Lauren',
        'Laussat',
        'Lawrence',
        'Lawton',
        'Le Conte',
        'Leavenworth',
        'Ledyard',
        'Lee',
        'Leese',
        'Legion',
        'Legion Of Honor',
        'Leidesdorff',
        'Leland',
        'Lendrum',
        'Lenox',
        'Leo',
        'Leona',
        'Leroy',
        'Lessing',
        'Lester',
        'Letterman',
        'Lettuce',
        'Levant',
        'Lexington',
        'Liberty',
        'Lick',
        'Liebig',
        'Liggett',
        'Lilac',
        'Lillian',
        'Lily',
        'Linares',
        'Lincoln',
        'Linda',
        'Linda Vista',
        'Linden',
        'Lindsay',
        'Lippard',
        'Lisbon',
        'Littlefield',
        'Livingston',
        'Lloyd',
        'Lobos',
        'Locksley',
        'Lockwood',
        'Locust',
        'Loehr',
        'Lois',
        'Loma Vista',
        'Lombard',
        'Lomita',
        'London',
        'Lone Mountain',
        'Long',
        'Long Bridge',
        'Longview',
        'Loomis',
        'Lopez',
        'Loraine',
        'Lori',
        'Los Palmos',
        'Lottie Bennett',
        'Louisburg',
        'Louisiana',
        'Lowell',
        'Lower',
        'Loyola',
        'Lucerne',
        'Lucky',
        'Lucy',
        'Ludlow',
        'Lulu',
        'Lunado',
        'Lundeen',
        'Lundys',
        'Lupine',
        'Lurline',
        'Lurmont',
        'Lusk',
        'Lydia',
        'Lyell',
        'Lynch',
        'Lyndhurst',
        'Lyon',
        'Lysette',
        'Mabel',
        'Mabini',
        'Mabrey',
        'Macalla',
        'Macarthur',
        'Macedonia',
        'Macky',
        'Macondray',
        'Maddux',
        'Madera',
        'Madison',
        'Madrid',
        'Madrone',
        'Magellan',
        'Magnolia',
        'Mahan',
        'Maiden',
        'Main',
        'Majestic',
        'Malden',
        'Mallorca',
        'Malosi',
        'Malta',
        'Malvina',
        'Manchester',
        'Mandalay',
        'Mangels',
        'Manor',
        'Manseau',
        'Mansell',
        'Mansfield',
        'Manzanita',
        'Maple',
        'Marcela',
        'Marcy',
        'Marengo',
        'Margaret',
        'Margrave',
        'Marietta',
        'Marin',
        'Marina',
        'Marina Green',
        'Marine',
        'Mariner',
        'Marion',
        'Mariposa',
        'Marist',
        'Mark',
        'Mark Twain',
        'Market',
        'Marlin',
        'Marne',
        'Mars',
        'Marshall',
        'Marsily',
        'Marston',
        'Martha',
        'Martin',
        'Martin Luther King Jr',
        'Martinez',
        'Marvel',
        'Marview',
        'Mary',
        'Mary Teresa',
        'Maryland',
        'Mason',
        'Masonic',
        'Massachusetts',
        'Massasoit',
        'Mateo',
        'Matthew',
        'Mauldin',
        'Maxwell',
        'Maybeck',
        'Mayfair',
        'Mayflower',
        'Maynard',
        'Maywood',
        'Mcallister',
        'Mccann',
        'Mccarthy',
        'Mccoppin',
        'Mccormick',
        'Mcdonald',
        'Mcdowell',
        'Mckinley',
        'Mckinnon',
        'Mclaren',
        'Mclea',
        'Mcnair',
        'Mcrae',
        'Meacham',
        'Meade',
        'Meadow',
        'Meadowbrook',
        'Meda',
        'Medau',
        'Medical Center',
        'Megan',
        'Melba',
        'Melra',
        'Melrose',
        'Mendell',
        'Mendosa',
        'Menoher',
        'Mercato',
        'Merced',
        'Mercedes',
        'Merchant',
        'Mercury',
        'Merlin',
        'Merriam',
        'Merrie',
        'Merrill',
        'Merrimac',
        'Merritt',
        'Mersey',
        'Mesa',
        'Metson',
        'Michigan',
        'Midcrest',
        'Middle Point',
        'Middle West',
        'Middlefield',
        'Midway',
        'Miguel',
        'Milan',
        'Miles',
        'Miley',
        'Mill',
        'Miller',
        'Milton',
        'Milton I Ross',
        'Minerva',
        'Minna',
        'Minnesota',
        'Mint',
        'Mirabel',
        'Miraloma',
        'Miramar',
        'Mirando',
        'Mission',
        'Mission Bay',
        'Mission Creek',
        'Mission Rock',
        'Mississippi',
        'Missouri',
        'Mistral',
        'Mizpah',
        'Modoc',
        'Moffitt',
        'Mojave',
        'Molimo',
        'Moncada',
        'Moneta',
        'Mono',
        'Montague',
        'Montalvo',
        'Montana',
        'Montcalm',
        'Montclair',
        'Monte Vista',
        'Montecito',
        'Monterey',
        'Montezuma',
        'Montgomery',
        'Monticello',
        'Monument',
        'Moore',
        'Moraga',
        'Moreland',
        'Morgan',
        'Morningside',
        'Morrell',
        'Morris',
        'Morse',
        'Morton',
        'Moscow',
        'Moss',
        'Moulton',
        'Moultrie',
        'Mount',
        'Mount Vernon',
        'Mountain Spring',
        'Mountview',
        'Mrs. Jackson',
        'Muir',
        'Mulford',
        'Mullen',
        'Munich',
        'Murray',
        'Museum',
        'Myra',
        'Myrtle',
        'Nadell',
        'Naglee',
        'Nahua',
        'Nancy Pelosi',
        'Nantucket',
        'Napier',
        'Naples',
        'Napoleon',
        'Natick',
        'Natoma',
        'Nauman',
        'Nautilus',
        'Navajo',
        'Navy',
        'Naylor',
        'Nebraska',
        'Nellie',
        'Nelson',
        'Nelson Rising',
        'Neptune',
        'Nevada',
        'New Montgomery',
        'Newburg',
        'Newcomb',
        'Newell',
        'Newhall',
        'Newman',
        'Newton',
        'Ney',
        'Niagara',
        'Niantic',
        'Nibbi',
        'Nichols',
        'Nido',
        'Nimitz',
        'Nob Hill',
        'Nobles',
        'Noe',
        'Nordhoff',
        'Norfolk',
        'Noriega',
        'Normandie',
        'North',
        'North 15Th',
        'North Gate',
        'North Hughes',
        'North Point',
        'North Van Horn',
        'North View',
        'Northgate',
        'Northpoint',
        'Northridge',
        'Northwood',
        'Norton',
        'Norwich',
        'Nottingham',
        'Nueva',
        'Oak',
        'Oak Access',
        'Oak Grove',
        'Oak Park',
        'Oakdale',
        'Oakhurst',
        'Oakwood',
        'Ocean',
        'Oceanview',
        'Octavia',
        'Odd Fellows',
        'Ofarrell',
        'Ogden',
        'Ohlone',
        'Old Chinatown',
        'Old Mason',
        'Olive',
        'Oliver',
        'Olmstead',
        'Olney',
        'Oloran',
        'Olympia',
        'Omar',
        'Oneida',
        'Onique',
        'Onondaga',
        'Opal',
        'Opalo',
        'Ophir',
        'Ora',
        'Orange',
        'Orben',
        'Ord',
        'Ordway',
        'Oreilly',
        'Oriole',
        'Orizaba',
        'Orsi',
        'Ortega',
        'Osage',
        'Oscar',
        'Osceola',
        'Osgood',
        'Oshaughnessy',
        'Otega',
        'Otis',
        'Otsego',
        'Ottawa',
        'Otter Cove',
        'Overlook',
        'Owen',
        'Owens',
        'Oxford',
        'Ozbourn',
        'Pacheco',
        'Pacific',
        'Pacifica',
        'Page',
        'Pagoda',
        'Palace',
        'Palm',
        'Palmetto',
        'Palo Alto',
        'Paloma',
        'Palos',
        'Palou',
        'Panama',
        'Panorama',
        'Paradise',
        'Paraiso',
        'Paramount',
        'Paris',
        'Park',
        'Park Hill',
        'Park Presidio',
        'Parker',
        'Parkhurst',
        'Parkridge',
        'Parnassus',
        'Parque',
        'Parsons',
        'Pasadena',
        'Passiflora',
        'Patten',
        'Patterson',
        'Patton',
        'Paul',
        'Paulding',
        'Payson',
        'Peabody',
        'Peacemakers',
        'Pearl',
        'Peek',
        'Pelican Cove',
        'Pelton',
        'Pemberton',
        'Pena',
        'Peninsula',
        'Pennington',
        'Pennsylvania',
        'Penny',
        'Peralta',
        'Perasto',
        'Perego',
        'Perimeter',
        'Perine',
        'Perry',
        'Pershing',
        'Persia',
        'Peru',
        'Peter Yorke',
        'Peters',
        'Petrarch',
        'Pfeiffer',
        'Phelps',
        'Phillips',
        'Phoenix',
        'Pico',
        'Piedmont',
        'Pierce',
        'Pierpoint',
        'Pilgrim',
        'Pinar',
        'Pine',
        'Pinehurst',
        'Pink',
        'Pino',
        'Pinto',
        'Pioche',
        'Piper',
        'Pixley',
        'Pizarro',
        'Plaza',
        'Pleasant',
        'Plum',
        'Plymouth',
        'Point Lobos',
        'Polaris',
        'Polk',
        'Pollard',
        'Pollock',
        'Pomona',
        'Pond',
        'Pontiac',
        'Pope',
        'Poplar',
        'Poppy',
        'Portal',
        'Porter',
        'Portola',
        'Portway',
        'Post',
        'Potomac',
        'Potrero',
        'Powell',
        'Powers',
        'Powhattan',
        'Prado',
        'Prague',
        'Pratt',
        'Precita',
        'Prentiss',
        'Prescott',
        'Presidio',
        'Pretor',
        'Priest',
        'Princeton',
        'Progress',
        'Prospect',
        'Prosper',
        'Public',
        'Pueblo',
        'Pulaski',
        'Putnam',
        'Quane',
        'Quarry',
        'Quartz',
        'Quebec',
        'Quesada',
        'Quickstep',
        'Quincy',
        'Quint',
        'Quintara',
        'R',
        'Raccoon',
        'Racine',
        'Radio',
        'Rae',
        'Raleigh',
        'Ralston',
        'Ramona',
        'Ramsel',
        'Ramsell',
        'Randall',
        'Randolph',
        'Rankin',
        'Rausch',
        'Ravenwood',
        'Rawles',
        'Rayburn',
        'Raycliff',
        'Raymond',
        'Reardon',
        'Rebecca',
        'Recycle',
        'Recycling Center Access',
        'Red Leaf',
        'Red Rock',
        'Reddy',
        'Redfield',
        'Redondo',
        'Redwood',
        'Reed',
        'Reeves',
        'Regent',
        'Reno',
        'Reposa',
        'Reservoir',
        'Restani',
        'Retiro',
        'Reuel',
        'Revere',
        'Rex',
        'Rey',
        'Rhine',
        'Rhode Island',
        'Rice',
        'Richard Henry Dana',
        'Richards',
        'Richardson',
        'Richland',
        'Richter',
        'Rickard',
        'Rico',
        'Ridge',
        'Ridgewood',
        'Riley',
        'Rincon',
        'Ringold',
        'Rio',
        'Rio Verde',
        'Ripley',
        'Ritch',
        'Rivas',
        'Rivera',
        'Riverton',
        'Rivoli',
        'Rizal',
        'Roach',
        'Roanoke',
        'Robblee',
        'Robert C Levy',
        'Robert Kirk',
        'Robinhood',
        'Robinson',
        'Rock',
        'Rockaway',
        'Rockdale',
        'Rockland',
        'Rockridge',
        'Rockwood',
        'Rod',
        'Rodgers',
        'Rodriguez',
        'Roemer',
        'Rolph',
        'Romain',
        'Rome',
        'Romolo',
        'Rondel',
        'Roosevelt',
        'Rosa Parks',
        'Roscoe',
        'Rose',
        'Rosella',
        'Roselyn',
        'Rosemary',
        'Rosemont',
        'Rosenkranz',
        'Rosewood',
        'Rosie Lee',
        'Ross',
        'Rossi',
        'Rossmoor',
        'Rotteck',
        'Rousseau',
        'Royal',
        'Ruckman',
        'Rudden',
        'Ruger',
        'Russ',
        'Russell',
        'Russia',
        'Russian Hill',
        'Ruth',
        'Rutland',
        'Rutledge',
        'Sabin',
        'Sacramento',
        'Saddleback',
        'Sadowa',
        'Safira',
        'Sagamore',
        'Saint Charles',
        'Saint Croix',
        'Saint Elmo',
        'Saint Francis',
        'Saint George',
        'Saint Germain',
        'Saint Josephs',
        'Saint Louis',
        'Saint Marys',
        'Sal',
        'Sala',
        'Salinas',
        'Salmon',
        'Samoset',
        'Sampson',
        'San Aleso',
        'San Andreas',
        'San Anselmo',
        'San Antonio',
        'San Benito',
        'San Bruno',
        'San Buenaventura',
        'San Carlos',
        'San Diego',
        'San Felipe',
        'San Fernando',
        'San Gabriel',
        'San Jacinto',
        'San Jose',
        'San Juan',
        'San Leandro',
        'San Lorenzo',
        'San Luis',
        'San Marcos',
        'San Miguel',
        'San Pablo',
        'San Rafael',
        'San Ramon',
        'Sanches',
        'Sanchez',
        'Sandpiper',
        'Sandpiper Cove',
        'Sansome',
        'Santa Ana',
        'Santa Barbara',
        'Santa Clara',
        'Santa Cruz',
        'Santa Fe',
        'Santa Marina',
        'Santa Monica',
        'Santa Paula',
        'Santa Rita',
        'Santa Rosa',
        'Santa Ynez',
        'Santa Ysabel',
        'Santiago',
        'Santos',
        'Sargent',
        'Saroyan',
        'Saturn',
        'Saul',
        'Sawyer',
        'Scenic',
        'Schofield',
        'School',
        'Schwerin',
        'Science',
        'Scotia',
        'Scotland',
        'Scott',
        'Sea View',
        'Seacliff',
        'Seal Cove',
        'Seal Rock',
        'Sears',
        'Seawell',
        'Second',
        'Security Pacific',
        'Selby',
        'Selma',
        'Seminole',
        'Seneca',
        'Sequoia',
        'Sergeant John V Young',
        'Serrano',
        'Service',
        'Seven Seas',
        'Severn',
        'Seville',
        'Seward',
        'Seymour',
        'Sfgh Access',
        'Shafter',
        'Shakespeare',
        'Shannon',
        'Sharon',
        'Sharp',
        'Shaw',
        'Shawnee',
        'Sheldon',
        'Shephard',
        'Sheridan',
        'Sherman',
        'Sherwood',
        'Shields',
        'Ship',
        'Shipley',
        'Shore View',
        'Short',
        'Shotwell',
        'Shoup',
        'Shrader',
        'Sibert',
        'Sibley',
        'Sickles',
        'Sierra',
        'Siesta',
        'Signal',
        'Silliman',
        'Silver',
        'Silverview',
        'Simonds',
        'Sixth',
        'Skyline',
        'Skyview',
        'Sloan',
        'Sloat',
        'Smith',
        'Sola',
        'Somerset',
        'Sonoma',
        'Sotelo',
        'Sotomayor',
        'Soule',
        'South',
        'South Gate',
        'South Hill',
        'South Hughes',
        'South Park',
        'South Van Horn',
        'South Van Ness',
        'Southard',
        'Southern Heights',
        'Southwood',
        'Sparrow',
        'Sparta',
        'Spear',
        'Spencer',
        'Spofford',
        'Spreckels Lake',
        'Spring',
        'Springfield',
        'Sproule',
        'Spruce',
        'Standish',
        'Stanford',
        'Stanford Heights',
        'Stanley',
        'Stanton',
        'Stanyan',
        'Staples',
        'Stark',
        'Starr King',
        'Starview',
        'State',
        'States',
        'Steiner',
        'Sterling',
        'Stern Grove',
        'Sternberg',
        'Steuart',
        'Steuben',
        'Steveloe',
        'Stevenson',
        'Still',
        'Stillings',
        'Stillman',
        'Stilwell',
        'Stockton',
        'Stone',
        'Stonecrest',
        'Stoneman',
        'Stoneridge',
        'Stoneybrook',
        'Stoneyford',
        'Storey',
        'Storrie',
        'Stow Lake',
        'Stratford',
        'Striped Bass',
        'Sturgeon',
        'Summit',
        'Sumner',
        'Sunbeam',
        'Sunglow',
        'Sunnydale',
        'Sunnyside',
        'Sunrise',
        'Sunset',
        'Sunset Blvd Off',
        'Sunset Blvd On',
        'Sunview',
        'Surrey',
        'Sussex',
        'Sutro Heights',
        'Sutter',
        'Sweeny',
        'Swiss',
        'Sycamore',
        'Sydney',
        'Sylvan',
        'Taber',
        'Tacoma',
        'Talbert',
        'Tamalpais',
        'Tampa',
        'Tandang Sora',
        'Tapia',
        'Tara',
        'Taraval',
        'Taylor',
        'Teddy',
        'Tehama',
        'Telegraph',
        'Telegraph Hill',
        'Temescal',
        'Temple',
        'Tennessee',
        'Tenny',
        'Teresita',
        'Terra Vista',
        'Terrace',
        'Terry A Francois',
        'Tevis',
        'Texas',
        'The Embarcadero',
        'Theresa',
        'Thomas',
        'Thomas Mellon',
        'Thomas More',
        'Thor',
        'Thornburg',
        'Thorne',
        'Thornton',
        'Thorp',
        'Thrift',
        'Tiffany',
        'Tillman',
        'Timothy Pflueger',
        'Tingley',
        'Tioga',
        'Tocoloma',
        'Todd',
        'Toland',
        'Toledo',
        'Toll Plaza Tunnel',
        'Tomaso',
        'Tompkins',
        'Toni Stone',
        'Tonquin',
        'Topaz',
        'Topeka',
        'Torney',
        'Torrens',
        'Touchard',
        'Towerside',
        'Townsend',
        'Toyon',
        'Trade Winds',
        'Trader Vic',
        'Trainor',
        'Transbay Hump',
        'Transbay Loop',
        'Transverse',
        'Treasure Island',
        'Treasury',
        'Treat',
        'Trenton',
        'Trinity',
        'Troy',
        'Truby',
        'Truett',
        'Trumbull',
        'Tubbs',
        'Tucker',
        'Tulane',
        'Tulare',
        'Tulip',
        'Tunnel',
        'Turk',
        'Turk Murphy',
        'Turner',
        'Turquoise',
        'Tuscany',
        'Twin Peaks',
        'Ulloa',
        'Underwood',
        'Union',
        'United Nations',
        'University',
        'Upland',
        'Upper',
        'Upper Service',
        'Upton',
        'Uranus',
        'Urbano',
        'Utah',
        'Valdez',
        'Vale',
        'Valencia',
        'Valerton',
        'Vallejo',
        'Valletta',
        'Valley',
        'Valmar',
        'Valparaiso',
        'Van Buren',
        'Van Dyke',
        'Van Keuren',
        'Van Ness',
        'Vandewater',
        'Vara',
        'Varela',
        'Varennes',
        'Varney',
        'Vasquez',
        'Vassar',
        'Vega',
        'Velasco',
        'Venard',
        'Ventura',
        'Venus',
        'Ver Mehr',
        'Verdi',
        'Verdun',
        'Vermont',
        'Verna',
        'Vernon',
        'Vesta',
        'Veterans',
        'Via Bufano',
        'Via Ferlinghetti',
        'Vicente',
        'Vicha Ratanapakdee',
        'Vicksburg',
        'Victoria',
        'Vidal',
        'Vienna',
        'Villa',
        'Vine',
        'Vinton',
        'Virgil',
        'Virginia',
        'Visitacion',
        'Vista',
        'Vista Verde',
        'Vista View',
        'Von Schmidt',
        'Vulcan',
        'Wabash',
        'Wagner',
        'Waithman',
        'Walbridge',
        'Waldo',
        'Walker',
        'Walkway',
        'Wall',
        'Wallace',
        'Wallen',
        'Waller',
        'Walnut',
        'Walter',
        'Walter U Lum',
        'Waltham',
        'Wanda',
        'Ward',
        'Ware',
        'Warner',
        'Warren',
        'Warriors',
        'Washburn',
        'Washington',
        'Watchman',
        'Water',
        'Waterfront',
        'Waterloo',
        'Waterville',
        'Watt',
        'Wattson',
        'Waverly',
        'Wawona',
        'Wayland',
        'Wayne',
        'Webb',
        'Webster',
        'Wedemeyer',
        'Weldon',
        'Welsh',
        'Wentworth',
        'West',
        'West Broadway',
        'West Clay',
        'West Crystal Cove',
        'West Halleck',
        'West Pacific',
        'West Point',
        'West Portal',
        'West View',
        'Westbrook',
        'Western Shore',
        'Westgate',
        'Westmoorland',
        'Weston',
        'Westside',
        'Westwood',
        'Wetmore',
        'Wheat',
        'Wheeler',
        'Whipple',
        'White',
        'Whitecliff',
        'Whitfield',
        'Whiting',
        'Whitney',
        'Whitney Young',
        'Whittier',
        'Wiese',
        'Wilde',
        'Wilder',
        'Wildwood',
        'Willard',
        'Williams',
        'Williar',
        'Willie B Kennedy',
        'Willow',
        'Wills',
        'Wilmot',
        'Wilson',
        'Winding',
        'Windsor',
        'Winfield',
        'Winn',
        'Winston',
        'Winter',
        'Winthrop',
        'Wisconsin',
        'Wisser',
        'Wood',
        'Woodacre',
        'Woodhaven',
        'Woodland',
        'Woodside',
        'Woodward',
        'Wool',
        'Woolsey',
        'Worcester',
        'Worden',
        'Worth',
        'Wren',
        'Wright',
        'Wurster',
        'Wyman',
        'Wyton',
        'Yacht',
        'Yale',
        'Yerba Buena',
        'Yorba',
        'York',
        'Yosemite',
        'Young',
        'Yukon',
        'Zampa',
        'Zanowitz',
        'Zeno',
        'Zircon',
        'Zoe',
        'Zoe Dell',
        'Zoo',
    ]
    street_suffix = [
        'Aly',
        'Ave',
        'Blvd',
        'Cir',
        'Ct',
        'Ctr',
        'Dr',
        'Hl',
        'Jct',
        'Ln',
        'Loop',
        'Park',
        'Pass',
        'Path',
        'Pkwy',
        'Pl',
        'Plz',
        'Pt',
        'Rd',
        'Row',
        'St',
        'Ter',
        'Trl',
        'Walk',
        'Way',
        'Xing',
    ]
    return f"{street_num} {random.choice(street_name)} {random.choice(street_suffix)}"


def generate_address_2():
    address = ["Apt", "Suite", "Unit"]
    return (
        f"{random.choice(address)} {random.randint(1,999)}"
        if random.random() < 0.14
        else None
    )


def generate_ssn_front():
    area_num = fake.random_number(digits=3, fix_len=True)
    group_num = fake.random_number(digits=2, fix_len=True)
    return f"{area_num}-{group_num}"


def generate_ssn_back():
    serial_num = fake.random_number(digits=4, fix_len=True)
    return serial_num


def generate_zip():
    zip_code = [
        "94105",
        "32801",
        "79904",
        "80204",
        "85004",
        "78701",
        "60604",
        "44286",
        "27605",
        "67335",
        "52163",
        "73564",
        "15662",
        "98244",
        "79041",
        "27283",
        "81639",
        "40507",
        "31816",
        "81635",
        "4761",
        "38220",
        "41093",
        "56621",
        "67485",
        "39653",
        "30701",
        "8215",
        "73481",
        "83318",
        "17857",
        "10981",
        "45333",
        "95612",
        "33956",
        "71415",
        "37153",
        "68344",
        "12526",
        "37204",
        "13732",
        "62613",
        "74857",
        "7462",
        "12784",
        "41555",
        "38966",
        "80729",
        "57424",
        "53004",
        "3284",
        "17361",
        "61949",
        "43414",
        "67335",
        "44608",
        "77445",
        "4912",
        "50240",
        "30349",
        "48045",
        "8314",
        "54867",
        "48308",
        "84039",
        "47612",
        "29911",
        "54479",
        "87939",
        "32361",
        "52590",
        "50072",
        "16136",
        "49845",
        "54101",
        "55411",
        "76233",
        "99668",
        "24658",
        "57225",
        "90047",
        "96054",
        "47280",
        "35064",
        "94928",
        "14892",
        "98834",
        "12961",
        "17580",
        "42170",
        "61859",
        "55049",
        "33870",
        "43944",
        "71220",
        "7064",
        "16036",
        "16636",
        "51025",
        "31312",
        "52748",
        "98829",
        "56142",
        "49748",
        "77562",
        "23605",
        "52253",
        "62815",
        "25562",
        "31562",
        "37721",
        "71341",
        "85381",
        "13679",
        "60525",
        "28303",
        "54767",
        "35768",
        "57436",
        "44840",
        "12469",
        "61417",
        "52754",
        "56588",
        "33051",
        "62048",
        "49920",
        "61743",
        "67111",
        "29590",
        "95488",
        "53104",
        "91743",
        "53119",
        "7080",
        "17318",
        "7630",
        "28638",
        "3076",
        "83873",
        "40322",
        "2766",
        "84314",
        "98921",
        "76836",
        "95824",
        "70501",
        "99829",
        "21136",
        "97845",
        "12975",
        "70584",
        "65611",
        "27052",
        "33266",
        "16220",
        "96929",
        "71102",
        "76369",
        "39165",
        "90717",
        "1236",
        "54209",
        "13760",
        "97732",
        "47280",
        "35752",
        "30117",
        "68855",
        "58261",
        "56310",
        "3830",
        "67647",
        "87746",
        "53066",
        "21009",
        "29568",
        "85016",
        "20181",
        "27829",
        "54977",
        "7452",
        "28337",
        "74369",
        "13346",
        "55359",
        "54452",
        "24138",
        "7901",
        "18447",
        "24867",
        "6057",
        "43228",
        "58369",
        "49962",
        "72575",
        "1071",
        "4672",
        "81323",
        "77017",
        "65339",
        "28750",
        "97840",
        "28086",
        "92277",
        "29831",
        "3223",
        "99702",
        "46797",
        "99102",
        "53015",
        "45333",
        "74354",
        "73447",
        "98070",
        "87931",
        "97479",
        "52158",
        "61041",
        "21035",
        "16911",
        "52216",
        "28577",
        "57054",
        "65612",
        "14891",
        "31532",
        "39067",
        "64430",
        "98125",
        "30668",
        "17572",
        "75956",
        "78960",
        "96750",
        "95459",
        "61956",
        "65020",
        "93624",
        "3741",
        "82324",
        "20667",
        "64456",
        "47354",
        "56043",
        "27258",
        "15380",
        "61356",
        "55128",
        "61345",
        "6405",
        "59465",
        "98350",
        "27524",
        "6250",
        "24539",
        "48441",
        "65037",
        "46076",
        "12167",
        "59339",
        "39457",
        "28217",
        "90037",
        "12734",
        "65026",
        "12193",
        "47388",
        "12015",
        "33131",
        "93940",
        "4945",
        "10307",
        "50255",
        "33511",
        "91747",
        "35577",
        "29147",
        "78147",
        "31707",
        "47596",
        "84327",
        "54824",
        "61262",
        "33598",
        "56762",
        "89142",
        "31313",
        "33936",
        "63736",
        "97344",
        "66833",
        "78674",
        "69132",
        "94971",
        "4240",
        "43556",
        "65333",
        "87701",
        "82218",
        "13634",
        "7875",
        "40358",
        "53579",
        "92369",
        "93925",
        "31019",
        "52358",
        "68508",
        "70513",
        "31303",
        "69154",
        "58554",
        "12009",
        "17862",
        "25075",
        "51525",
        "93245",
        "10464",
        "17774",
        "61545",
        "83546",
        "93664",
        "16738",
        "34242",
        "32807",
        "32724",
        "45142",
        "46985",
        "45365",
        "2356",
        "15456",
        "47330",
        "15035",
        "19486",
        "58016",
        "50428",
        "74030",
        "13328",
        "12860",
        "23070",
        "54902",
        "54849",
        "3450",
        "38614",
        "72959",
        "64076",
        "15106",
        "38329",
        "46390",
        "1538",
        "26802",
        "15329",
        "73487",
        "83311",
        "58031",
        "37825",
        "99730",
        "99750",
        "23937",
        "78562",
        "77565",
        "12854",
        "82515",
        "43130",
        "45380",
        "92253",
        "25140",
        "36740",
        "68926",
        "62480",
        "84761",
        "75694",
        "70631",
        "41031",
        "36765",
        "98674",
        "57054",
        "43457",
        "16370",
        "52766",
        "95525",
        "42366",
        "88401",
        "55711",
        "16662",
        "70559",
        "48759",
        "46524",
        "99921",
        "63966",
        "95368",
        "28333",
        "47868",
        "43981",
        "5056",
        "97137",
        "28649",
        "32654",
        "97206",
        "43717",
        "36445",
        "13648",
        "63957",
        "33133",
        "14588",
        "20036",
        "48892",
        "27960",
        "85942",
        "95717",
        "14463",
        "38746",
        "47021",
        "28684",
        "40507",
        "64847",
        "13658",
        "71419",
        "57541",
        "30083",
        "28725",
        "28721",
        "5739",
        "93268",
        "69001",
        "66538",
        "23487",
        "4572",
        "21084",
        "57364",
        "7628",
        "37663",
        "98665",
        "47875",
        "75475",
        "21555",
        "73029",
        "13642",
        "37711",
        "13803",
        "70714",
        "80532",
        "78349",
        "75140",
        "61278",
        "19977",
        "88038",
        "44272",
        "97071",
        "13691",
        "24185",
        "66510",
        "94940",
        "94035",
        "56362",
        "52216",
        "62363",
        "23924",
        "62832",
        "72550",
        "4912",
        "59831",
        "95528",
        "44074",
        "97039",
        "38940",
        "18405",
        "77360",
        "20720",
        "61430",
        "55111",
        "37356",
        "7756",
        "13814",
        "59317",
        "45119",
        "80239",
        "80420",
        "56320",
        "89317",
        "29851",
        "28352",
        "20877",
    ]
    return f"{random.choice(zip_code)}"

all_data = []

records = 1248548
for i in tqdm(range(records)):
    first_name = fake.first_name()
    last_name = fake.last_name()

    start_date = datetime(1970, 1, 1)
    end_date = datetime(2023, 7, 12)
    hire_date_math = start_date + timedelta(
        days=random.randint(0, (end_date - start_date).days)
    )
    years_to_subtract = random.randint(1, 80)
    birth_date_math = hire_date_math - timedelta(days=years_to_subtract * 365)

    if random.random() < 0.45:
        termination_date_math = start_date + timedelta(
            days=random.randint(0, (end_date - start_date).days)
        )
    else:
        termination_date_math = None

    hire_date = hire_date_math.strftime("%Y-%m-%d")
    birth_date = birth_date_math.strftime("%Y-%m-%d")
    birth_year = birth_date[:4]
    domain_name = "@example.com"
    first_email = [
        first_name.lower(),
        first_name[0].lower(),
        last_name.lower(),
        last_name[0].lower(),
        fake.safe_color_name().lower(),
        fake.word().lower(),
        fake.building_number(),
        fake.street_suffix().lower(),
    ]

    spacing_email = ["_", ".", ""]
    first_choice = random.choice(first_email)
    second_email = random.choice([name for name in first_email if name != first_choice])
    if random.random() <.89:
        second_choice = second_email
    else:
        second_choice = ""
    
    third_email = birth_year

    if random.random() < 0.36:
        forth_choice = third_email
    else:
        forth_choice = ""

    email = f"{first_choice}{random.choice(spacing_email)}{second_email}{forth_choice}{domain_name}"

    emp_id = i + 1
    emp_secondary_id = i + 1

    all_data.append(
        [
            emp_secondary_id,
            first_name,
            generate_middle(),
            last_name,
            generate_suffix(),
            birth_date,
            hire_date,
            termination_date_math,
            email,
            str(generate_phone()),
            generate_address(),
            generate_address_2(),
            fake.city(),
            fake.state_abbr(),
            generate_zip().zfill(5),
            generate_ssn_front(),
            generate_ssn_back(),
        ]
    )

df_all_data = pd.DataFrame(
    all_data,
    columns=[
        "emp_secondary_id",
        "first_name",
        "middle_name",
        "last_name",
        "suffix",
        "date_of_birth",
        "hire_date",
        "termination_date",
        "email",
        "phone",
        "address",
        "address_2",
        "city",
        "state",
        "zip_code",
        "encrypted_tax_a",
        "tax_b",
    ],
)

df_all_data = df_all_data.sort_values("hire_date")
df_all_data["emp_id"] = range(1, len(df_all_data) + 1)
df_all_data["emp_secondary_id"] = [f"A{i:08}" for i in range(1, len(df_all_data) + 1)]

df_emp_info = df_all_data[["emp_id", "emp_secondary_id", "first_name", "middle_name", "last_name", "suffix", "date_of_birth", "termination_date", "hire_date"]].copy()
df_emp_contact = df_all_data[["emp_id", "email", "phone", "address", "address_2", "city", "state", "zip_code"]].copy()
df_emp_tax = df_all_data[["emp_id", "encrypted_tax_a", "tax_b"]].copy()

dataframes = [
    (df_emp_info, "emp_info.csv"),
    (df_emp_contact, "emp_contact.csv"),
    (df_emp_tax, "emp_tax.csv"),
]

for df, filename in tqdm(dataframes):
    df.to_csv(filename, index=False)

print("Data generation complete!")
